import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Header />
        <main className="px-px-6 sm:px-10 md:px-16">
          <div className="w-full max-w-5xl mx-auto">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
